<?php

namespace service\models;
use common\models\RadioShaftModel;
use Yii;

class RadioShaft extends RadioShaftModel
{
    public function fields()
    {
        $fields =  parent::fields(); // TODO: Change the autogenerated stub
        // pass

        return $fields;
    }

}
