<?php

namespace service\models;
use common\models\SuggestionModel;
use common\models\SuggestionPicModel;
use common\models\UserModel;
use Yii;

class Suggestion extends SuggestionModel
{
    public function fields()
    {
        $fields =  parent::fields(); // TODO: Change the autogenerated stub
        $fields['nick_name'] = function (){
            return UserModel::find()->select('nick_name')->where(['id' => $this->user_id])->scalar() ?: '';
        };

        $fields['pics'] = function (){
            $pics = SuggestionPicModel::find()->select('id,img_url')->where(['suggestion_id' => $this->id])->asArray()->all();
            return $pics;
        };

        return $fields;
    }

}
