<?php

namespace service\models;
use common\models\UserModel;
use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id ID
 * @property string $mobile 手机号
 * @property string $password 密码
 * @property string $access_token 通行证
 * @property string $nick_name 昵称
 * @property string $wechat_token 微信openid
 * @property string $qq_token qq_openid
 * @property string $avatar_image 头像
 * @property string $register_time 注册时间
 * @property string $last_login_time 最后一次登录时间
 * @property int $register_ip 注册ip
 * @property int $last_login_ip 最后一次登录ip
 * @property int $status 状态
 * @property string $device_id 设备号
 * @property int $os 1a,2i,3w,4o
 * @property int $login_time 登录次数
 * @property int $active 激活
 * @property string $active_time 激活时间
 * @property int $conceal_hide 隐私,1显示 0隐藏
 */
class User extends UserModel
{
    public function fields()
    {
        $fields = parent::fields();

        $fields['register_ip'] = function(){
            return long2ip($this->register_ip);
        };

        return $fields; // TODO: Change the autogenerated stub
    }


}
