<?php

namespace api\controllers;

use common\models\Common;
use common\models\Jusheng;
use common\models\JushengCouponModel;
use common\models\JushengLogModel;
use common\models\JushengVipModel;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;

/*
 * 巨省会员对接   他们调用我们
 * */
class JushengController extends CommonController
{
    public $modelClass = '';
    public $jusheng;

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);
        // 话费券编码：347BE7835B0E5423C4760FEA7A8A7807  5元
        // 话费券编码：AEAAA39EFCB84BD2D201FB1E1488C18D  10元
        // 视频券编码：CC9E205C150269A92116537966167BC2  2周视频劵 20元的
        $this->jusheng = new Jusheng();
    }

    public function beforeAction($action)
    {
        $data = $action->controller->post;
        try{
            if(!empty($data)){
                $request_ip = Common::getClientIp();
                $action_name = $action->id; // 控制动作
                $data = json_encode($data);
                $js_log = new JushengLogModel();
                $js_log->content = $data;
                $js_log->create_time = date('Y-m-d H:i:s');
                $js_log->action_name = $action_name;
                $js_log->ip = $request_ip;
                $js_log->save();
            }
        }catch (\Exception $e){
            // pass
        }catch (\Throwable $e){
            // pass
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                HttpBearerAuth::className(),
                QueryParamAuth::className(),
            ],
            'except' => ['test','query-vip','push-coupon-status','query-coupon-available','test-check-coupon','test-sign']
        ];
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['delete'], $actions['create'], $actions['update'], $actions['index'],$actions['view']);
        return $actions;
    }

    // 给第三方测试用
    public function actionTestSign(){
        $post = $this->post();
        $this->jusheng->parseData($post);
        $this->jusheng->response("0000","验签成功", ['success' => 'success']);
    }

    // 会员信息查询
    public function actionQueryVip(){
        $post = $this->post();
        $data = $this->jusheng->parseData($post);
//        $data = ['userId' => "1"]; // 模拟解析出来的数据
        $user_id = $data['userId'];
        $user_vip_model = JushengVipModel::find()->where(['user_id' => $user_id])->andWhere(['>=','expire_time',date('Y-m-d H:i:s')])->one();

        $not_vip = [
            'isVip' => "0",
            'vipType' => "1",  // 默认都是新会员
            'vipExpireTime' => ""
        ];
        if(!$user_vip_model) $this->jusheng->response("0000","", $not_vip);

        $is_vip = [
            'isVip' => "1",
            'vipType' => "1",  // 默认都是新会员
            'vipExpireTime' => $user_vip_model->expire_time
        ];
        $this->jusheng->response("0000","", $is_vip);
    }

    /*
     * 巨省推送劵信息到我们这
     * */
    public function actionPushCouponStatus(){
        $post = $this->post();
        $data = $this->jusheng->parseData($post);
        // 模拟数据
//        $data = '[{
//          "couponCode": "ASDEW231SADSAD",
//          "userId":"2",
//          "supplierCouponCode": "CC9E205C150269A92116537966167BC2",
//          "couponStatus":"1"
//        },{
//          "couponCode": "XAWA1SADEFW",
//          "userId":"1",
//          "supplierCouponCode": "CC9E205C150269A92116537966167BC2",
//          "couponStatus":"1"
//        }]';
//        $data = json_decode($data,true);
        $res = [];
        foreach ($data as $k=>$v){
            $list = [];
            $list['couponCode'] = $v['couponCode'];
            $list['userId'] = $v['userId'];

            $jc_model = JushengCouponModel::find()->where(['coupon_code' => $v['couponCode'], 'user_id' => $v['userId'], 'supplier_coupon_code' => $v['supplierCouponCode']])->one();
            if($jc_model){
                $list['couponStatus'] = "SUCCESS";
                $jc_model->coupon_status = $v['couponStatus'];
                $jc_model->save();
            }else{
                $list['couponStatus'] = "FAIL";
            }
            $res[] = $list;
        }

        $this->jusheng->response("0000",'success', $res);
    }

    // 巨省查询劵是否可用
    public function actionQueryCouponAvailable(){
        $post = $this->post();
        $data = $this->jusheng->parseData($post);
        // 模拟数据
//        $data = [
//            "couponCode" => "XAWA1SADEFW",
//            "userId"=>"1",
//            "supplierCouponCode" => "CC9E205C150269A92116537966167BC2"
//        ];
        $model = JushengCouponModel::find()->where(['coupon_code' => $data['couponCode'], 'user_id' => $data['userId'], 'supplier_coupon_code' => $data['supplierCouponCode']])
                                           ->andWhere(['>=','end_time',date('Y-m-d H:i:s')])
                                           ->andWhere(['<=','start_time',date('Y-m-d H:i:s')])
                                           ->one();
        if($model){
            $res = [
                'couponStatus' => $model->coupon_status
            ];
            $this->jusheng->response("0000","success",$res);
        }
        $this->jusheng->response("0001","劵无效或已过期");
    }


    /*
     * 以下是我们调用他们
     * */
    // 我方模拟会员信息推送
    public function actionTestVipPush(){
        $user_id = "11";
        $data = [
            'userId' => $user_id,
            'vipType' => '1',
            'vipExpireTime' => '2020-06-29 00:00:00'
        ];
        $data = $this->jusheng->getData('/appweb/data/ws/rest/vip/agent/customer/push', $data);
        var_dump($data);exit();
        $jusheng_vip_id = $data['userId'];
        $jusheng_vip_model = JushengVipModel::find()->where(['user_id' => $user_id])->one();
        $jusheng_vip_model->jusheng_vip_id = $jusheng_vip_id;
        $jusheng_vip_model->save();
        exit();
    }

    // 我方查询劵的使用情况  对账使用
    public function actionTestCheckCoupon(){
        $data = '[{
          "couponCode": "xxxxx",
          "userId":"xxxxx",
          "supplierCouponCode": "xxxx"
        },{
          "couponCode": "xxxxx1",
          "userId":"xxxxx1",
          "supplierCouponCode": "xxxx1"
        }]';
        $data = json_decode($data,true);
        $res = $this->jusheng->getData('/appweb/data/ws/rest/vip/agent/coupon/status', $data);
        var_dump($res);
        exit();
    }
    /*
     * 以上是我们调用他们测试
     * */


}
