<?php

namespace api\models;
use common\models\ArticleTypeModel;
use common\models\ArticleTypeSubscriptionModel;

use Yii;


class ArticleType extends ArticleTypeModel
{
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        unset($fields['is_del']);

        $fields['is_sub'] = function(){
            $user_id = Yii::$app->params['__web']['user_id'];
            $data = ArticleTypeSubscriptionModel::find()->where(['user_id' => $user_id])->andWhere(['article_type_id' => $this->at_id])->one();
            if($data) return 1;
            return 0;
        };


        return $fields;
    }

}
