<?php

namespace api\models;
use common\models\ArticleReportModel;

use Yii;

class ArticleReport extends ArticleReportModel
{
    public function fields()
    {
      return parent::fields(); // TODO: Change the autogenerated stub
    }
}
