<?php

namespace api\models;
use common\models\InformDynamicModel;
use Yii;

class InformDynamic extends InformDynamicModel
{
    public function fields()
    {
        $fields =  parent::fields(); // TODO: Change the autogenerated stub


        return $fields;
    }

}

