<?php

namespace api\models;
use common\models\UserBlacklistModel;
use Yii;

class UserBlacklist extends UserBlacklistModel
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}
